# Generated by Django 6.1.1 on 2026-10-09 01:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите рабочий email (будет использоваться для входа)",
                        max_length=254,
                        unique=True,
                        verbose_name="Почта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Введите номер телефона в международном формате (+7 XXX XXX-XX-XX)",
                        max_length=20,
                        null=True,
                        validators=[users.models.validate_phone],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите аватар (форматы: JPG, PNG, GIF; максимум 2 МБ)",
                        null=True,
                        upload_to="users/avatars",
                        validators=[users.models.validate_avatar_extension, users.models.validate_avatar_size],
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Указывает, может ли пользователь войти в систему",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Разрешает доступ к админ‑панели", verbose_name="Персонал"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, help_text="Предоставляет все права", verbose_name="Суперпользователь"
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации")),
                (
                    "tg_chat_id",
                    models.CharField(
                        blank=True,
                        help_text="Введите ID чата в Telegram",
                        max_length=50,
                        null=True,
                        verbose_name="ID чата в Telegram",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted "
                                  "to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
