# Generated by Django 6.1.1 on 2026-10-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("p_name", models.CharField(max_length=100, verbose_name="Название принтера")),
                ("p_cartridge", models.CharField(max_length=100, verbose_name="Картридж для принтера")),
            ],
            options={
                "verbose_name": "Принтер АРМа",
                "verbose_name_plural": "Принтеры АРМа",
                "ordering": ("p_name",),
            },
        ),
    ]
