# Generated by Django 6.1.1 on 2026-10-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kii",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("k_vp_name", models.CharField(max_length=15, unique=True, verbose_name="АП ВипНета")),
                ("k_dl_name", models.CharField(max_length=15, unique=True, verbose_name="Номер DallasLock")),
                ("k_crypto", models.CharField(max_length=15, unique=True, verbose_name="Версия Криптопро")),
            ],
            options={
                "verbose_name": "Данные по КИИ",
                "verbose_name_plural": "Данные по КИИ",
            },
        ),
    ]
