# Generated by Django 6.1.1 on 2026-10-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("office_number", models.CharField(max_length=10, unique=True, verbose_name="Номер кабинета")),
                ("office_level", models.CharField(max_length=2, unique=True, verbose_name="Тип подразделения")),
                ("office_name", models.CharField(max_length=100, verbose_name="Название кабинета")),
                ("office_arm", models.CharField(max_length=20, verbose_name="Название арма в кабинете")),
            ],
            options={
                "verbose_name": "Кабинет",
                "verbose_name_plural": "Кабинеты",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="OfficeLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("office_level", models.CharField(max_length=2, unique=True, verbose_name="Тип подразделения")),
                ("office_level_name", models.CharField(max_length=20, verbose_name="Наименование подразделения")),
            ],
        ),
    ]
