# Generated by Django 6.1.1 on 2026-10-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="office",
            options={"ordering": ("office_number",), "verbose_name": "Кабинет", "verbose_name_plural": "Кабинеты"},
        ),
        migrations.AlterField(
            model_name="office",
            name="office_level",
            field=models.CharField(max_length=5, unique=True, verbose_name="Тип подразделения"),
        ),
        migrations.AlterField(
            model_name="officelevel",
            name="office_level",
            field=models.CharField(max_length=5, unique=True, verbose_name="Тип подразделения"),
        ),
    ]
