# Generated by Django 6.1.1 on 2026-10-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0002_alter_office_options_alter_office_office_level_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OfficeLevel",
        ),
        migrations.RemoveField(
            model_name="office",
            name="office_level",
        ),
    ]
