# Generated by Django 6.1.1 on 2026-10-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("c_name", models.CharField(max_length=100, verbose_name="Название компьютера")),
                ("c_ddr", models.CharField(max_length=6, verbose_name="Память ДДР XXX Gb")),
                ("c_hdd", models.CharField(max_length=100, verbose_name="Память HDD")),
                ("c_os", models.CharField(max_length=12, verbose_name="Операционная система")),
                ("c_install", models.DateField(null=True, verbose_name="Дата установки")),
            ],
            options={
                "verbose_name": "Компьютер АРМа",
                "verbose_name_plural": "Компьютеры АРМа",
                "ordering": ("c_name", "c_install"),
            },
        ),
    ]
