# Generated by Django 6.1.1 on 2026-10-09 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comp", "0001_initial"),
        ("kii", "0001_initial"),
        ("office", "0001_initial"),
        ("printer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workplace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("w_worker", models.CharField(max_length=50, unique=True, verbose_name="Работник АРМа")),
                (
                    "w_level",
                    models.IntegerField(
                        choices=[(0, "Уровень 0"), (1, "Уровень 1"), (2, "Уровень 2"), (3, "Уровень 3")],
                        default=0,
                        verbose_name="Уровень АРМа",
                    ),
                ),
                ("w_ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP адрес")),
                ("w_hostname", models.CharField(max_length=30, unique=True, verbose_name="Название АРМа")),
                ("w_display", models.CharField(blank=True, max_length=50, verbose_name="Монитор")),
                ("w_cn", models.CharField(blank=True, max_length=30, verbose_name="Номер кабинета")),
                ("w_on", models.CharField(max_length=5, verbose_name="Отделение")),
                (
                    "w_inv_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Инв. номер"),
                ),
                (
                    "w_ser_number",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Серийный номер"),
                ),
                (
                    "w_seat_number",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="Номер места/стола"),
                ),
                (
                    "w_status",
                    models.CharField(
                        choices=[
                            ("active", "В работе"),
                            ("maintenance", "На обслуживании"),
                            ("decommissioned", "Списан"),
                            ("reserved", "Зарезервирован"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("w_last_updated", models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления")),
                (
                    "w_comp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comps_workplaces",
                        to="comp.comp",
                    ),
                ),
                (
                    "w_kii",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="kii_ids", to="kii.kii"
                    ),
                ),
                (
                    "w_office",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offices_workplaces",
                        to="office.office",
                    ),
                ),
                (
                    "w_printer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printers_workplaces",
                        to="printer.printer",
                    ),
                ),
            ],
            options={
                "verbose_name": "АРМ",
                "verbose_name_plural": "АРМы",
                "ordering": ["w_hostname"],
            },
        ),
    ]
