# Generated by Django 6.1.1 on 2026-10-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printer", "0001_initial"),
        ("workplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="w_printer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="printers_workplaces",
                to="printer.printer",
            ),
        ),
    ]
