# Generated by Django 6.1.1 on 2026-10-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workplace", "0002_alter_workplace_w_printer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workplace",
            name="w_cn",
        ),
        migrations.RemoveField(
            model_name="workplace",
            name="w_on",
        ),
    ]
