# Generated by Django 6.1.1 on 2026-10-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplace", "0003_remove_workplace_w_cn_remove_workplace_w_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="w_level",
            field=models.IntegerField(
                choices=[(0, "Уровень 0"), (1, "Уровень 1"), (2, "Уровень 2")], default=0, verbose_name="Уровень АРМа"
            ),
        ),
    ]
