# Generated by Django 6.1.1 on 2026-10-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplace", "0004_alter_workplace_w_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="w_level",
            field=models.IntegerField(
                choices=[(0, "АХЧ"), (1, "ПОЛИКЛИНИКА"), (2, "CТАЦИОНАР"), (3, "ПРОЧИЕ")],
                default=0,
                verbose_name="Уровень АРМа",
            ),
        ),
    ]
