# Generated by Django 6.1.1 on 2026-10-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplace", "0005_alter_workplace_w_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="w_hostname",
            field=models.CharField(default="WRK", max_length=10, verbose_name="ХОСТ АРМа"),
        ),
    ]
